fixtures:
  repositories:
    archive:
      repo: "https://github.com/camptocamp/puppet-archive.git"
      ref: "0.9.0"
    concat:
      repo: "https://github.com/puppetlabs/puppetlabs-concat.git"
      ref: "5.0.0"
    logrotate:
      repo: "https://github.com/yo61/puppet-logrotate.git"
      ref: "v1.4.0"
    stdlib:
      repo: "https://github.com/puppetlabs/puppetlabs-stdlib.git"
      ref: "4.15.0"
  symlinks:
    duplicity: "#{source_dir}"

