fixtures:
  forge_modules:
    archive:
      repo: "puppet/archive"
      ref: "2.2.0"
    concat:
      repo: "puppetlabs/concat"
      ref: "4.1.1"
    logrotate:
      repo: "puppet-logrotate"
      ref: "3.1.0"
    stdlib:
      repo: "puppetlabs/stdlib"
      ref: "4.24.0"

  symlinks:
    duplicity: "#{source_dir}"

