name 'tohuwabohu-duplicity'
version '1.0.0'
source 'https://github.com/tohuwabohu/tohuwabohu-duplicity.git'
project_page 'https://github.com/tohuwabohu/tohuwabohu-duplicity'
author 'Martin Meinhold'
license 'Apache License, Version 2.0'
summary 'Install and manage duplicity'
description ''

dependency 'rodjek/logrotate', '1.x'
dependency 'example42/puppi', '2.x'
dependency 'puppetlabs/stdlib', '4.x'
dependency 'gini/archive', '0.2.x'
