name 'tohuwabohu-duplicity'
version '1.0.0'
source 'https://github.com/tohuwabohu/puppet-duplicity.git'
project_page 'https://github.com/tohuwabohu/puppet-duplicity'
author 'Martin Meinhold'
license 'Apache License, Version 2.0'
summary 'Install and manage duplicity'
description ''

dependency 'gini/archive', '0.2.x'
dependency 'puppetlabs/concat', '>= 1.1.0 < 2.0.0'
dependency 'puppetlabs/stdlib', '>= 4.2.0 < 5.0.0'
dependency 'rodjek/logrotate', '1.x'
